version: "3"
services:
    app:
        container_name: "webinar-backend"
        image: "rangganast/webinar-backend"
        depends_on:
            - "db"
        ports:
            - "3000:3000"
        env_file:
            - .env
        environment:
            - "DB_DEV_HOST=db"

    db:
        container_name: "db"
        image: "postgres:12"
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=postgres"
            - "POSTGRES_DB=webinar_backend"
        ports:
            - "5432:5432"